### ISSUE TITLE
Incorrect number of red/blue/neutral cards

### ISSUE THREAD

**Issue by cevn** [eraether/WatchWordBot#4] opened 2016-06-17 03:14 UTC
Today, we've played multiple games where blue has had 5-6 cards when red has had 2 or more over them. Maybe the bug is around here somewhere? https://github.com/eraether/WatchWordBot/blob/master/src/main/java/com/raether/watchwordbot/BuildableWatchWordGrid.java#L38-L43

**Comment by eraether** [comment] 2016-06-17 03:15
Yep, the issue is that the
        List<Integer> unassignedTileIndicies = getUnassignedTileIndicies();
is outside the while loop, so it is likely to reassign cards to the same index.  Putting it inside the while loop should fix the issue.

**Closed as completed** 2016-06-17 16:57 UTC
